-- =====================================================================
-- File: create_emp_schema_employee_objects.sql
--
-- Purpose:
-- Create an application schema (EMP_SCHEMA), required privileges,
-- sequence, and EMPLOYEE table in Oracle 19c.
--
-- Notes:
-- - In Oracle, a schema is equivalent to a database user
-- - There is no CREATE SCHEMA IF NOT EXISTS in Oracle
-- - This script assumes execution as SYSDBA for user creation
-- - Object creation can be done either as SYS or as EMP_SCHEMA
-- =====================================================================


-- =====================================================================
-- STEP 1: Create application schema (user)
-- Run this section as SYSDBA
-- =====================================================================

-- Create user (schema owner)
CREATE USER emp_schema IDENTIFIED BY emp_password;

-- Grant basic connectivity
GRANT CONNECT TO emp_schema;

-- Grant object creation privileges
GRANT RESOURCE TO emp_schema;
GRANT CREATE SEQUENCE TO emp_schema;

-- (Optional but common in dev environments)
GRANT CREATE VIEW TO emp_schema;

-- At this point, EMP_SCHEMA exists and can own objects


-- =====================================================================
-- STEP 2: Create sequence for EMPLOYEE primary key
-- Can be run as SYS or EMP_SCHEMA
-- =====================================================================

CREATE SEQUENCE emp_schema.employee_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Sequence created for manual or trigger-based ID generation


-- =====================================================================
-- STEP 3: Create EMPLOYEE table
-- =====================================================================

CREATE TABLE emp_schema.employee (
    id         NUMBER PRIMARY KEY,
    name       VARCHAR2(100) NOT NULL,
    department VARCHAR2(50),
    salary     NUMBER(10, 2)
);

-- Table EMPLOYEE created under EMP_SCHEMA


-- =====================================================================
-- STEP 4 (OPTIONAL): Auto-generate ID using trigger
-- Use this if you want MySQL-style auto-increment behavior
-- =====================================================================

CREATE OR REPLACE TRIGGER emp_schema.employee_bi
BEFORE INSERT ON emp_schema.employee
FOR EACH ROW
WHEN (new.id IS NULL)
BEGIN
    :new.id := emp_schema.employee_seq.NEXTVAL;
END;
/

-- Trigger ensures ID is populated automatically on INSERT


-- =====================================================================
-- STEP 5: Verification queries (optional)
-- =====================================================================

-- Verify user
-- SELECT username FROM dba_users WHERE username = 'EMP_SCHEMA';

-- Verify table
-- SELECT table_name FROM all_tables WHERE owner = 'EMP_SCHEMA';

-- Verify sequence
-- SELECT sequence_name FROM all_sequences WHERE sequence_owner = 'EMP_SCHEMA';

-- Sample insert (ID will be auto-generated by trigger)
-- INSERT INTO emp_schema.employee (name, department, salary)
-- VALUES ('Amit', 'IT', 75000);

-- COMMIT;


-- =====================================================================
-- END OF SCRIPT
-- =====================================================================
